openapi: 3.0.0
info:
  title: Mongo Express API with Swagger
  version: 1.0.0
  description: A simple API using MongoDB, Express, and Swagger

paths:
  /todos:
    get:
      summary: Retrieves all todos
      description: Fetches all todo items from the database, returning an array of todos.
      responses:
        "200":
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
        "500":
          description: Server error

    post:
      summary: Create a new todo
      description: Adds a new todo item to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
      responses:
        "201":
          description: Returns the created todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "400":
          description: Validation error
        "500":
          description: Server error

    delete:
      summary: Deletes a todo
      description: Deletes a todo item from the database by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The todo ID
      responses:
        "200":
          description: Returns the deleted todo's ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
        "404":
          description: Todo not found
        "500":
          description: Server error

components:
  schemas:
    Todo:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier for the todo item
        text:
          type: string
          description: The text of the todo item
        completed:
          type: boolean
          description: The completion status of the todo item
        createdAt:
          type: string
          format: date-time
          description: The time at which the todo item was created
      required:
        - text
